# Generated by Django 2.2.7 on 2019-11-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191111_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Scopes',
        ),
    ]
