# Generated by Django 2.2.7 on 2019-11-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191111_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='scopes',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.Tags'),
        ),
    ]
