# Generated by Django 2.1.1 on 2019-11-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191111_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scopes', to='articles.Tags'),
        ),
    ]
