# Generated by Django 2.1.1 on 2019-11-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopes',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='основное'),
        ),
    ]
